services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gr-api
    user: "1000:1000"
    env_file:
      - .env
    environment:
      CI: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/pnpm-store
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine@sha256:b0f9560a2de083e2cc7382e75f808c7381a32852a7ec49117deedb300e552b24
    container_name: gr-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  node_modules:
  pnpm-store:
  postgres_data:
